FROM eclipse-temurin:17-jre-focal

WORKDIR /opt/fione

COPY fione-serving.jar /opt/fione
COPY model.zip /opt/fione

RUN groupadd -r fione && useradd -r -g fione fione && \
    chown -R fione /opt/fione && \
    echo "#!/bin/bash\nexec java -jar /opt/fione/fione-serving.jar" > /usr/bin/serve && \
    chmod +x /usr/bin/serve

ENV MODEL_PATH /opt/fione/model.zip

CMD ["/bin/bash", "/usr/bin/serve"]
